language: python

python:
    - "3.6"
    # - "3.7" see https://github.com/travis-ci/travis-ci/issues/9815
    - "2.7"
    - "pypy"

sudo: false

install:
    - pip install tox-travis
    - pip install coveralls

script: tox

after_success: coveralls
